// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmsService.Model;

namespace SmsService.Model.Migrations
{
    [DbContext(typeof(SMSContext))]
    partial class SMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmsService.Model.Model.CountryCodes", b =>
                {
                    b.Property<short>("MCC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(10) CHARACTER SET utf8mb4")
                        .HasMaxLength(10);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,3)");

                    b.HasKey("MCC");

                    b.ToTable("CountryCodes");

                    b.HasData(
                        new
                        {
                            MCC = (short)262,
                            Country = "Germany",
                            CountryCode = "49",
                            Price = 0.055m
                        },
                        new
                        {
                            MCC = (short)232,
                            Country = "Austria",
                            CountryCode = "43",
                            Price = 0.053m
                        },
                        new
                        {
                            MCC = (short)260,
                            Country = "Poland",
                            CountryCode = "48",
                            Price = 0.032m
                        });
                });

            modelBuilder.Entity("SmsService.Model.Model.SMSMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MCC")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(5,3)");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<DateTime>("SendDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("SMSMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
